
name: travel_reimbursement
description: Travel Reimbursement Demo
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  logger: ^2.6.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
